### ISSUE TITLE
nav buttons

### ISSUE THREAD

**Issue by KyloRenRS** [awbridgers/runescapeCalculator#13]
If the calculators are each on their own webpages, there should be links to go back to the main page from each calculator, not just links to go to the specific calc pages

**Comment by KyloRenRS** [comment]
Something like `<a href='../'>Go back to main page</a>` should do the trick

**Comment by awbridgers** [comment]
Hey thats pretty smart

**Comment by KyloRenRS** [comment]
Looks like the last couple of commits resolved this. Closing
